export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_SINGLE_REQUEST = 'PRODUCT_SINGLE_REQUEST'
export const PRODUCT_SINGLE_SUCCESS = 'PRODUCT_SINGLE_SUCCESS'
export const PRODUCT_SINGLE_FAIL = 'PRODUCT_SINGLE_FAIL'
